title: 'I Am Ryan Smith'
default_lang: en
author:
  name: 'Ryan Smith'
  email: rrs209@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'A website for presenting and highlighting the skills and experiences of Ryan R. Smith'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
